//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 9/10/2021 12:22:23 AM
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MicroTechTask
{
    public partial interface IAccountRepository
    {
        Task<List<Account>> GetTopLevelAccounts();
        Task<Account> GetAccountDetails(string accountNumber);
    }
}
