//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 9/10/2021 12:22:23 AM
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace MicroTechTask
{
    public partial class AccountRepository
    {

        public async Task<List<Account>> GetTopLevelAccounts()
        {
            var result = await objectSet.Include(a => a.ChildAccounts).ThenInclude(a => a.ChildAccounts).ThenInclude(a => a.ChildAccounts).Where( a => a.ACCParent == null && !a.Balance.HasValue).ToListAsync();

            return result;
        }

        public async Task<Account> GetAccountDetails(string accountNumber)
        {
            var result = await objectSet.Include(a => a.ChildAccounts).ThenInclude(a => a.ChildAccounts).ThenInclude(a => a.ChildAccounts).Where(a => a.ACCParent == null && !a.Balance.HasValue).SingleOrDefaultAsync( a => a.AccNumber == accountNumber);

            return result;
        }
    }
}
