//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 9/10/2021 12:23:33 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace MicroTechTask
{
    public partial class Account {

        public Account()
        {
            this.ChildAccounts = new List<Account>();
            OnCreated();
        }

        public virtual string AccNumber { get; set; }

        public virtual string ACCParent { get; set; }

        public virtual decimal? Balance { get; set; }

        public virtual IList<Account> ChildAccounts { get; set; }

        public virtual Account ParentAccount { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
